//这里就可以引用你要显示的页面了
import index from '@/view/login/index.vue'
import intro from '@/view/login/intro.vue'
import alert from "@/view/login/alert"
import password from "@/view/login/password";
import fireWall from "../view/questions/fireWall";
import emailAttack from "../view/questions/emailAttack";
import repassword from "../view/questions/repassword";
import wifiAttack from "../view/questions/wifiAttack";
import transferData from "../view/questions/transferData";
import lunchTime from "../view/questions/lunchTime";
import shoppingOnline from "../view/questions/shoppingOnline";
import socialAttachment from "../view/questions/socialAttachment";
import aliPay from "../view/questions/aliPay";
import pdfPrint from "../view/questions/pdfPrint";
import socialFreshMan from "../view/questions/socialFreshMan";
import outsideBusinessTalk from "../view/questions/outsideBusinessTalk";
import fireWallData from "../view/questions/fireWallData";
import windowPopup from "../view/questions/windowPopup";
import WelcomeProcess from "../view/login/WelcomeProcess";
import trainStaffs from "../view/environment/trainStaffs";
import lastReport from "../view/environment/lastReport";
import promotion from "../view/environment/promotion";
import lunchTimeWrong from "../view/wrong/lunchTimeWrong";
import lunchToTransfer from "../view/environment/lunchToTransfer";
import transferDataWrong from "../view/wrong/transferDataWrong";
import transferToshopping from "../view/environment/transferToshopping";
import shoppingTOWifi from "../view/environment/shoppingTOWifi";
import onlineShoppingWrong from "../view/wrong/onlineShoppingWrong";
import wifiAttackWrong from "../view/wrong/wifiAttackWrong";
import wifiToPdf from "../view/environment/wifiToPdf";
import pdfPrintWrong from "../view/wrong/pdfPrintWrong";
import promotion1 from "../view/environment/promotion1";
import Alipaybefore from "../view/environment/Alipaybefore";
import aliPayWrong from "../view/wrong/aliPayWrong";
import alipayToEmailAttack from "../view/environment/alipayToEmailAttack";
import emailAttackWrong from "../view/wrong/emailAttackWrong";
import emailToFireWall from "../view/environment/emailToFireWall";
import firewalldataWrong from "../view/wrong/firewalldataWrong";
import fireWallWrong from "../view/wrong/fireWallWrong";
import firewallToSocial from "../view/environment/firewallToSocial";
import socialFreshMantopromotionTwo from "../view/environment/socialFreshMantopromotionTwo";
import socialAttachTofirewalldata from "../view/environment/socialAttachTofirewalldata";
import socialAttachWrong from "../view/wrong/socialAttachWrong";
import socailFreshManWrong from "../view/wrong/socailFreshManWrong";
import projectOneToRepass from "../view/environment/projectOneToRepass";
import projectTwo from "../view/environment/projectTwo";
import outsideBusinessWrong from "../view/wrong/outsideBusinessWrong";
import fireDataToWindowpop from "../view/environment/fireDataToWindowpop";
import windowsUpWrong from "../view/wrong/windowsUpWrong";
import Finish from "../view/environment/Finish";
import BagsShopping from "@/view/environment/BagsShopping";
import carShopping from "@/view/environment/carShopping";
import businessToSocialAttach from "@/view/environment/businessToSocialAttach";
//配置路由，path就是你浏览器地址，component就是跟着你要显示的页面，/表示默认地址。
export default [
  {path: "/", component: index},
  {path: "/intro", component: intro},
  {path: "/alert", component: alert},
  {path: "/aliPay", component: aliPay},
  {path: "/password", component: password},
  {path: "/lunchTime", component: lunchTime},
  {path: "/fireWall", component: fireWall},
  {path: "/emailAttack", component: emailAttack},
  {path: "/shoppingOnline", component: shoppingOnline},
  {path: "/repassword", component: repassword},
  {path: "/wifiAttack", component: wifiAttack},
  {path: "/transferData", component: transferData},
  {path: "/shoppingOnline", component: shoppingOnline},
  {path: "/pdfPrint", component: pdfPrint},
  {path: "/socialFreshMan", component: socialFreshMan},
  {path: "/outsideBusinessTalk", component: outsideBusinessTalk},
  {path: "/socialAttachment", component: socialAttachment},
  {path: "/fireWallData", component: fireWallData},
  {path: "/windowPopup", component: windowPopup},
  {path: "/WelcomeProcess", component: WelcomeProcess},
  {path: "/trainStaffs", component: trainStaffs},
  {path: "/trainStaffs", component: trainStaffs},
  {path: "/lastReport", component: lastReport},
  {path: "/promotion", component: promotion},
  {path: "/lunchTimeWrong", component: lunchTimeWrong},
  {path: "/lunchToTransfer", component: lunchToTransfer},
  {path: "/transferDataWrong", component: transferDataWrong},
  {path: "/transferToshopping", component: transferToshopping},
  {path: "/shoppingTOWifi", component: shoppingTOWifi},
  {path: "/onlineShoppingWrong", component: onlineShoppingWrong},
  {path: "/wifiAttackWrong", component: wifiAttackWrong},
  {path: "/wifiToPdf", component: wifiToPdf},
  {path: "/pdfPrintWrong", component: pdfPrintWrong},
  {path: "/promotion1", component: promotion1},
  {path: "/Alipaybefore", component: Alipaybefore},
  {path: "/aliPayWrong", component: aliPayWrong},
  {path: "/alipayToEmailAttack", component: alipayToEmailAttack},
  {path: "/emailAttackWrong", component: emailAttackWrong},
  {path: "/emailToFireWall", component: emailToFireWall},
  {path: "/fireWallWrong", component: fireWallWrong},
  {path: "/firewalldataWrong", component: firewalldataWrong},
  {path: "/firewallToSocial", component: firewallToSocial},
  {path: "/socailFreshManWrong", component: socailFreshManWrong},
  {path: "/socialFreshMantopromotionTwo", component: socialFreshMantopromotionTwo},
  {path: "/socialAttachTofirewalldata", component: socialAttachTofirewalldata},
  {path: "/socialAttachWrong", component: socialAttachWrong},
  {path: "/projectTwo", component: projectTwo},
  {path: "/projectOneToRepass", component: projectOneToRepass},
  {path: "/outsideBusinessWrong", component: outsideBusinessWrong},
  {path: "/fireDataToWindowpop", component: fireDataToWindowpop},
  {path: "/windowsUpWrong", component: windowsUpWrong},
  {path: "/Finish", component: Finish},
  {path: "/BagsShopping", component: BagsShopping},
  {path: "/carShopping", component: carShopping},
  {path: "/businessToSocialAttach", component: businessToSocialAttach},
]
